version: "3"

tasks:
  deps:
    cmds:
      - go mod download

  clean:
    cmds:
      - go clean -testcache
      - rm -rf ./build/out

  serve-restSimpleApp:
    cmds:
      - PORT=$PORT build/out/restSimpleApp

  serve-proxyApp:
    cmds:
      - PROXY_PORT=$PROXY_PORT build/out/proxyApp

  compile-restSimpleApp:
    cmds:
      - go build -a -o ./build/out/restSimpleApp cmd/restSimpleApp/main.go

  package-restSimpleApp:
    cmds:
      - docker build --file build/restSimpleApp/Dockerfile -t hiteshpattanayak/rest-simple-app:2.0 .

  publish-restSimpleApp:
    cmds:
      - docker push hiteshpattanayak/rest-simple-app:2.0

  compile-proxyApp:
    cmds:
      - go build -a -o ./build/out/proxyApp cmd/proxyApp/main.go

  package-proxyApp:
    cmds:
      - docker build --file build/proxyApp/Dockerfile -t hiteshpattanayak/proxy-app:3.0 .

  publish-proxyApp:
    cmds:
      - docker push hiteshpattanayak/proxy-app:3.0
