version: "3"

tasks:
  compile-restSimpleApp:
    cmds:
      - go build -a -o ./build/out/restSimpleApp cmd/restSimpleApp/main.go

  deps:
    cmds:
      - go mod download

  clean:
    cmds:
      - go clean -testcache
      - rm -rf ./build/out

  package-restSimpleApp:
    cmds:
      - docker build --file build/Dockerfile -t hiteshpattanayak/rest-simple-app:2.0 .

  publish-restSimpleApp:
    cmds:
      - docker push hiteshpattanayak/rest-simple-app:2.0
